name: Budget_Buddy
description: A finance tracking app for iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  
  # UI
  cupertino_icons: ^1.0.5
  flutter_slidable: ^2.0.0
  fl_chart: ^0.55.0
  
  # Database
  sqflite: ^2.2.8+4
  path: ^1.8.3
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  
  # Backup/Export Functionality
  permission_handler: ^10.4.3
  path_provider: ^2.1.1
  file_picker: ^5.3.3
  csv: ^5.0.2
  share_plus: ^7.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true